version: '3.8'

services:
  postgres:
    image: postgis/postgis:14-3.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: road_capacity
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: always

  fastapi:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - ./app:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/road_capacity
      - OSRM_SERVER_URL=http://host.docker.internal:5000
    restart: always

volumes:
  postgres_data: